name: Check plugin updates

on:
  schedule:
    - cron: '0 2 * * *'  # каждый день в 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Check for module updates
        run: |
          go list -m -u all | grep -v "(latest)" || echo "No updates"
          go get -u ./...
          go mod tidy

      - name: Check if there are any changes
        id: changes
        run: |
          git diff --quiet || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Commit updated go.mod/go.sum
        if: steps.changes.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): update Caddy plugins"
          branch: main